eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/api/menu/**
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - AuthenticationFilter

        - id: kitchen-service
          uri: lb://kitchen-service
          predicates:
            - Path=/api/kitchen/**
          filters:
            - AuthenticationFilter

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/auth/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/noti/**
          filters:
            - AuthenticationFilter

        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/delivery/**
          filters:
            - AuthenticationFilter

        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

