server:
  error:
    include-message: always
    include-binding-errors: always
  port: 0

spring:
  data:
    mongodb:
        port: 27017
        host: localhost
        database: Menu
  application:
    name: menu-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
